name: Deploy ui

on:
  push:
    branches: [ "c4t" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Build
      run: |
        cd ui
        yarn --frozen-lockfile
        yarn build

    - name: Deploy to Apillon
      env:
        APILLON_API_KEY: ${{ secrets.APILLON_API_KEY }}
        APILLON_API_SECRET: ${{ secrets.APILLON_API_SECRET }}
        WEBSITE_UUID: ${{ secrets.APILLON_WEBSITE_UUID }}
      run: |
        npm i -g @apillon/cli
        apillon hosting deploy-website ./ui/dist --uuid $WEBSITE_UUID --key $APILLON_API_KEY --secret $APILLON_API_SECRET